baseURL = "https://poligon-edu.ro/"
title = "Poligon Educational"
theme = "hugo-book"


disableKinds = ["taxonomy"]

# Language Inversion Defaults
defaultContentLanguage = "ro"
defaultContentLanguageInSubdir = false

# ==========================================
# GLOBAL LAYOUT SETTINGS
# ==========================================
[params]
BookTheme = "auto"
BookToC = true
BookSearch = true
BookLogo = "images/logo.png"
BookKatex = true
BookFavicon = "images/favicon.png"
BookSection = "*"

# ==========================================
# SPLIT CONTENT ARCHITECTURE
# ==========================================
[languages]
[languages.ro]
label = "Română"
contentDir = "content/ro"
weight = 1

[languages.en]
label = "English"
contentDir = "content/en"
weight = 2

# ==========================================
# MARKUP PARSER ENGINE
# ==========================================
[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = "gruvbox"
noClasses = true

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$'], ['\\[', '\\]']]
inline = [['$', '$'], ['\\(', '\\)']]
# ==========================================
# THIRD-PARTY SERVICES
# ==========================================
[services]
[services.googleAnalytics]
id = "G-2SJLNGNK0T"
